"""ui /settings — ver docs/ARCHITECTURE.md para contratos y dependencias."""

from .. import config
from ..ui import preview
from bpy.props import BoolProperty
from bpy.props import EnumProperty
from bpy.props import FloatProperty
from bpy.props import IntProperty
from bpy.props import StringProperty
import bpy


class RuinSettings(bpy.types.PropertyGroup):
    interior_layout: EnumProperty(name='Habitaciones',items=[('OPEN','Planta abierta','Sin tabiques interiores'),('TWO','Dos estancias','Estancia de acceso y habitación trasera'),('THREE','Tres estancias','Dos cuartos conectados mediante distribuidor trasero')],default='OPEN')
    damage_enabled: BoolProperty(name='Activar daño',description='Desactiva derrumbes, agujeros, roturas, desgaste y escombros sin borrar sus ajustes; independiente de la calidad',default=True)
    hole_seed: IntProperty(name='Distribución de agujeros',description='Semilla independiente del bloqueo del aparejo; cambia la colocación en todas las paredes',default=0,min=0,max=999999)
    roof_damage: FloatProperty(name='Rotura de cubierta',description='Sectores perdidos con rastreles rotos y escombros asociados',default=0,min=0,max=1)
    chimneys: BoolProperty(name='Chimenea',description='Hogar abierto desde planta baja, conducto hueco y paso resuelto por forjado y tejas; necesita un tramo libre de vanos y escalera',default=False)
    brass_pipes: BoolProperty(name='Canalones y bajantes',description='Latón envejecido junto a aleros y paños libres de huecos',default=False)
    roof_gables: BoolProperty(name='Cerrar hastiales',description='Frentes con revoco grueso retranqueado y entramado de montantes y riostras',default=True)
    roof_curve: FloatProperty(name='Curvatura del tejado',description='Pendiente cóncava: más suave junto al alero, más inclinada en la cumbrera',default=.6,min=0,max=1)
    roof_tiles: BoolProperty(name='Tejas solapadas',description='Medias cañas con espesor, solape y cumbrera curva sobre rastreles; requiere armazón',default=False)
    stair_type: EnumProperty(name='Escalera',items=[('NONE','Ninguna',''),('STONE','Piedra','Tramo macizo de piedra'),('WOOD','Madera','Peldaños sobre zancas de madera')],default='NONE')
    stair_side: EnumProperty(name='Ascenso',items=[('RIGHT','Hacia derecha','Mirando desde la fachada'),('LEFT','Hacia izquierda','Mirando desde la fachada')],default='RIGHT')
    wood_damage: FloatProperty(name='Deterioro de madera',description='Pudrición, fisuras longitudinales y bordes astillados en toda la carpintería',default=.35,min=0,max=1)
    roof_frame: BoolProperty(name='Armazón de tejado',description='Cerchas curvas, correas y rastreles sobre paredes con apoyo',default=False)
    window_facing: EnumProperty(name='Cara del marco',items=[('OUTSIDE','Exterior','Marco saliente hacia la fachada'),('INSIDE','Interior','Invierte el marco hacia la habitación')],default='OUTSIDE')
    ground_floor: BoolProperty(name='Suelo de planta baja',description='Tablones y rastreles dentro de una habitación cerrada',default=True)
    upper_floor: BoolProperty(name='Suelo de entreplanta',description='Tablones apoyados sobre las vigas disponibles',default=True)
    floor_damage: FloatProperty(name='Rotura del suelo',default=.25,min=0,max=1)
    export_density: FloatProperty(name='Densidad del sólido',description='Fracción de detalle conservada antes de fusionar; 0,35 equilibra tamaño y acabado',default=.35,min=.15,max=1)
    window_width: FloatProperty(name='Ancho de ventana (mm)',default=15,min=10,max=40)
    window_height: FloatProperty(name='Alto de ventana (mm)',default=16,min=12,max=34)
    balconies: BoolProperty(name='Balcones superiores',description='Plataforma y barandilla en huecos de la planta superior que dispongan de apoyo',default=False)
    iron_mode: EnumProperty(name='Herrajes',items=[('TWIST','Torcidos','Barrotes enteros, deformados'),('BROKEN','Partidos','Barrotes rotos con extremos sujetos')],default='TWIST')
    iron_damage: EnumProperty(name='Intensidad del hierro',items=[('1','Leve',''),('2','Media',''),('3','Alta','')],default='1')
    use_instances: BoolProperty(name='Arrays + Geometry Nodes',description='Reutiliza variantes de piedra; conserva mallas únicas junto a roturas y aberturas. Recomendado para habitaciones',default=True)
    batch_preview: BoolProperty(name='Agrupar por tramos',description='Vista con pocas mallas; conserva IDs de ladrillo. La exportación reconstruye piezas completas',default=True)
    microdetail_preview: BoolProperty(name='Microrelieve en vista',description='Añade poros y subdivisión fina también al editar: mucho más costoso. Al preparar Detalle siempre se aplica',default=False)
    build_type: EnumProperty(name='Construcción',items=[('PARTITION','Tabique','6 mm de grosor'),('WALL','Pared','9 mm de grosor'),('FORTRESS','Muralla','15 mm de grosor')],default='WALL')
    height_type: EnumProperty(name='Altura',items=[('RUIN','Baja','Ruina baja: 27 mm de alto'),('ONE','1 planta','57 mm de alto'),('TWO','2 plantas','112 mm de alto, nivel intermedio a 57 mm')],default='ONE')
    layout_mode: EnumProperty(name='Paredes',description='Paredes contiguas que forman L, U o habitación',items=[('NONE','Ninguna','Un muro'),('ONE','1 pared','Forma de L'),('TWO','2 paredes','Forma de U'),('ROOM','Habitación','Cuatro paredes sin cubierta')],default='NONE')
    building_depth: FloatProperty(name='Fondo (mm)',default=50,min=40,max=240)
    extra_side: EnumProperty(name='Lado',description='Lado de la pared contigua en forma de L',items=[('LEFT','Izquierdo',''),('RIGHT','Derecho','')],default='RIGHT')
    windows_enabled: BoolProperty(name='Ventanas',default=False)
    windows_per_wall: IntProperty(name='Por pared',description='Ventanas por pared; se limitan por apoyos y espacio',default=1,min=1,max=3)
    floor_beams: BoolProperty(name='Vigas de entreplanta',default=True)
    show_advanced: BoolProperty(name='Ajustes avanzados',default=False)

    door_leaf: BoolProperty(name='Hoja de puerta',description='Añade tablones, refuerzos y anilla; cierra el paso de puerta',default=True)
    left_turn: EnumProperty(name='Extremo izquierdo',items=config.TURN_ITEMS,default='NONE')
    right_turn: EnumProperty(name='Extremo derecho',items=config.TURN_ITEMS,default='NONE')
    left_return_length: FloatProperty(name='Longitud tramo izquierdo (mm)',default=30,min=15,max=70)
    right_return_length: FloatProperty(name='Longitud tramo derecho (mm)',default=30,min=15,max=70)

    rubble_amount: FloatProperty(name='Escombros',description='Desde pocos ladrillos hasta un cúmulo de tierra, fragmentos y grava',default=.35,min=0,max=1)
    ground_roughness: FloatProperty(name='Tierra y grava',description='Relieve de suelo y cantidad de pequeñas piedras',default=.65,min=0,max=1)
    wood_frame: BoolProperty(name='Marco de madera',default=True)
    wood_grain: FloatProperty(name='Vetas',description='Relieve de las vetas de la madera',default=.7,min=0,max=1)

    preview_quality: EnumProperty(name='Edición',description='Calidad de la vista previa mientras editas',items=config.QUALITY_ITEMS,default='WORK')
    export_quality: EnumProperty(name='Exportación',description='Calidad al preparar el sólido; Detalle añade el relieve fino para resina',items=config.QUALITY_ITEMS,default='DETAIL')
    quick_edit: BoolProperty(name='Vista rápida',description='Mientras ajustas, muestra primero Borrador y después refina en la calidad de edición',default=True)
    lock_distribution: BoolProperty(name='Bloquear distribución',default=True,update=preview.distribution_changed)
    distribution_seed: IntProperty(default=17)
    randomness: FloatProperty(name='Irregularidad',description='Intensidad de la variación de forma de las piedras',default=1,min=0,max=1)
    cracks_per_stone: IntProperty(name='Por piedra',description='Máximo de grietas por piedra',default=3,min=1,max=3)
    crack_length_var: FloatProperty(name='Longitud',description='Variabilidad de la longitud de las grietas',default=.7,min=0,max=1)
    crack_width_var: FloatProperty(name='Anchura',description='Variabilidad de la anchura de las grietas',default=.6,min=0,max=1)
    crack_angle_var: FloatProperty(name='Rotación',description='Variabilidad del ángulo de las grietas',default=.85,min=0,max=1)
    crack_path_var: FloatProperty(name='Recorrido',description='Cuánto zigzaguea el trazo de las grietas',default=.7,min=0,max=1)
    door_enabled: BoolProperty(name='Tramo con puerta',default=False)
    door_position: FloatProperty(name='Posición',description='Posición de la puerta a lo largo del muro',default=.5,min=0,max=1)
    door_width: FloatProperty(name='Anchura (mm)',description='Anchura del hueco de la puerta',default=32,min=16,max=50)
    door_height: FloatProperty(name='Altura (mm)',description='Altura del hueco de la puerta',default=34,min=12,max=65)
    connection_enabled: BoolProperty(name='Pilares de conexión',default=False)
    connection_side: EnumProperty(name='Extremo',items=[('LEFT','Izquierdo',''),('RIGHT','Derecho',''),('BOTH','Ambos','')],default='BOTH')
    live_preview: BoolProperty(name='Vista previa automática',default=True,update=preview.settings_changed)
    status: StringProperty(default='Ajusta un deslizador para previsualizar',options={'SKIP_SAVE'})
    length: FloatProperty(name='Longitud (mm)',default=120,min=60,max=240)
    height: FloatProperty(name='Altura máxima (mm)',default=52,min=25,max=160)
    left_height: FloatProperty(name='Extremo izquierdo (mm)',default=55,min=12,max=160)
    right_height: FloatProperty(name='Extremo derecho (mm)',default=40,min=12,max=160)
    thickness: FloatProperty(name='Grosor nominal (mm)',default=12,min=6,max=22)
    stone_size: FloatProperty(name='Altura de hilada (mm)',default=6.5,min=4,max=10)
    stone_variation: FloatProperty(name='Anchuras',description='Variación de anchura entre piedras',default=.2,min=0,max=1)
    bond_subdivisions: IntProperty(name='Subdivisiones',description='Piezas por módulo en las hiladas alternas; limita piezas demasiado estrechas',default=1,min=1,max=3)
    alternate_height: FloatProperty(name='Hiladas alternas',description='Proporción de altura alterna; conserva la altura total y evita hiladas menores de 3 mm',default=1.0,min=.6,max=1.4)
    projection: FloatProperty(name='Saliente de piedras (mm)',default=1.2,min=0,max=3)
    pillar_count: IntProperty(name='Pilares',description='Número de pilares intermedios',default=2,min=0,max=5)
    pillar_width: FloatProperty(name='Anchura de pilares (mm)',default=12,min=9,max=16)
    hole_count: IntProperty(name='Agujeros por pared',description='Máximo por pared, limitado por espacio y contactos estructurales',default=2,min=0,max=6)
    hole_size: FloatProperty(name='Tamaño (mm)',description='Tamaño de los agujeros',default=14,min=7,max=30)
    collapse: FloatProperty(name='Derrumbe',description='Zonas de colapso en todas las paredes, pilares y perforaciones en suelos',default=.76,min=0,max=1)
    break_position: FloatProperty(name='Posición',description='Posición del derrumbe a lo largo del muro',default=.72,min=.25,max=.85)
    wear_level: EnumProperty(name='Desgaste',default='MEDIUM',items=[('LIGHT','Ligero','Aristas algo gastadas'),('MEDIUM','Medio','Erosión visible en caras y aristas'),('HEAVY','Fuerte','Piedra muy envejecida'),('CUSTOM','Personalizado','Conserva la intensidad elegida al regenerar')])
    wear: FloatProperty(name='Intensidad',description='Desgaste personalizado en Detalle: 0 sin erosión, 1 máximo',default=.55,min=0,max=1)
    cracks: FloatProperty(name='Grietas',description='Cantidad de grietas y desconchados',default=.6,min=0,max=1)
    hole_damage: FloatProperty(name='Rotura en bordes',default=.7,min=0,max=1)
    seed: IntProperty(name='Semilla',default=17,min=0,max=999999)
